version: "3.3"
services:
  backend:
    build: .
    container_name: backend
    ports: 
      - "3000:3000"
  mysql:
    image: mysql:5.7
    container_name: db-mysql
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports: 
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_PASSWORD: 'admin-password'
      MYSQL_USERNAME: 'admin'
      MYSQL_DATABASE: 'dqfs'
